# Generator for the 2026-08-21 cycle/contrastive ablation fleet (16 arms x 8
# GPUs = 128). Motivation: the Stage-0 probe recipe (delta-token CE, frozen
# trunk) learns instruction<->trajectory ranking (val acc 0.548, chance 0.25),
# while every co-training attempt so far (full-span CE, w=0.2) learned nothing
# AND wrecked the main task — including the 08-19 GT-warmup Phase-A arms
# (val cycle_loss pinned at 0.2*ln4 uniform floor, val route 1.10-1.60 vs 0.24
# baseline), so the planned Phase-B-from-warmup-ckpt design is dead. This
# fleet isolates WHICH probe ingredient rescues co-training:
#   axis 1: delta-token CE on/off        (arms *_fullspan vs *_delta)
#   axis 2: cycle weight 0.2/0.05/0.01   (gradient-scale hypothesis proxy)
#   axis 3: detach (explainer-only) vs undetached (closed-loop)
#   axis 4: GT-reader arms (gt_traj=true, the Phase-A redo done right)
# plus controls (placebo shuffle, 0.3m-noise steganography tripwire), 2 seeds
# on the central w=0.05 pair, and a matched-bs contrastive-InfoNCE family for
# the loss-approach comparison. Baseline comparators already exist with S3
# ckpts: nfso8q / 8nauws (smoke_cycle_base_w0_bs1{,_s7}).
# All arms: bs=1, K=4, grad ckpt, 2 epochs, non-preemptible, S3 ckpt upload.
import pathlib

TEMPLATE = """# AUTO-GENERATED by gen_abl_fleet.py (2026-08-21 ablation fleet) — edit the
# generator, not this file. Arm: {desc}
# Launch: .venv/bin/python lilypad/launch.py simlingo_lilypad/configs/{fname}
name: {job}
model_identifier: other.training.alpamayo15.default.v1
ignore_idle_reaper: true
workload_variant_config:
  workload_type: "training"
  training_fn: simlingo_lilypad.run.smoke_train
  training_fn_config:
    s3_bucket: "research-datasets-chicago"
    s3_prefix: "hf-datasets/RenzKa/simlingo"
    workdir: "/mnt/work/simlingo_smoke"
    hydra_overrides:
      - experiment=simlingo_seed1
      - data_module=carla_no_buckets
      - max_epochs=2
      - val_every_n_epochs=1
      # bs=1: cycle pass OOMs at bs=2 (y35tq3/a1flqu); keeps all arms matched
      - data_module.batch_size=1
      - data_module.num_workers=8
      - data_module.base_dataset.use_safety_flag=false
      - data_module.base_dataset.dreamer_contrastive=true
      - data_module.base_dataset.dreamer_contrastive_k=4
      - model.language_model.gradient_checkpointing=true
{overrides}
      - wandb_project=simlingo-contrastive
      - name={wandb}
  experiment_tracker:
    wandb:
      entity: research
      project: simlingo-contrastive

cluster_resources:
  gpu_machine_type: a100.8
  num_gpus: 8
  customer_resource: research
  # eviction = total restart (resume not auto-wired); short runs, keep them
  # deterministic — same reasoning as every cycle smoke since d39e5d1
  preemptible: never
  allowed_regions:
    - us-chicago-1
  requeue_if_preempted: true

runtime_environment:
  # torch pip install ~3 GB + 54 GB dataset extract before first GPU step
  setup_timeout_seconds: 3600

  required_environment_variables:
    - HF_TOKEN

  constant_environment_variables:
    AWS_REQUEST_CHECKSUM_CALCULATION: when_required
    AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
    AWS_ENDPOINT_URL_S3: "https://idskhu5vqvtl.compat.objectstorage.us-chicago-1.oraclecloud.com"
    AWS_DEFAULT_REGION: us-chicago-1
    PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:True"
    SIMLINGO_EXPECTED_OBJECTS: "121"
    CHECKPOINT_S3_PREFIX: "s3://research-datasets-chicago/simlingo-checkpoints"

  code_assets:
    root_directory: .
    pip_requirements_path: simlingo_lilypad/requirements.txt
    # default 10MB silently drops all_as_augmented.json (13.3MB) -> crash
    max_file_size_mb: 20
    regex_excludes:
      - "^/.venv/"
      - "^/third_party/"
      - "^/autovla/"
      - "^/masking/"
      - "^/code_as_a_reward/"
      - "^/perplexity/"
      - "^/dpo_pairs/"
      - "^/build_wds/"
      - "^/mnist/"
      - "^/research-core/"
      - "^/docker/"
      - "^/lockfiles/"
      - "^/jspace/"
      - "^/bench2drive/"
      - "^/simlingo/simlingo/Bench2Drive/"
      - "^/simlingo/simlingo/leaderboard"
      - "^/simlingo/simlingo/scenario_runner"
      - "^/simlingo/simlingo/team_code/"
      - "^/simlingo/simlingo/dataset_generation/"
"""

def cyc(w, detach, delta=True, gt=False, shuffle=False, noise=0.0, seed=None):
    o = []
    if gt:
        o.append("model.cycle_use_gt_traj=true")
    o += [
        f"model.cycle_loss_weight={w}",
        f"model.cycle_detach={'true' if detach else 'false'}",
        "model.cycle_warmup_steps=1000",  # gen-3 value, kept for comparability
    ]
    if delta:
        o.append("model.cycle_delta_token_ce=true")
    if shuffle:
        o.append("model.cycle_shuffle_traj=true")
    if noise:
        o.append(f"model.cycle_traj_noise_m={noise}")
    if seed is not None:
        o.append(f"seed={seed}")
    return o

def con(w, cycle=None, seed=None):
    o = [f"model.contrastive_loss_weight={w}"]
    if cycle:
        o += cycle
    if seed is not None:
        o.append(f"seed={seed}")
    return o

ARMS = [
    # tag, description, override list
    ("cyc_det_delta_w0.2",    "gen-3 detached rerun + delta-token CE (isolates delta-CE effect vs girvw1)", cyc(0.2, True)),
    ("cyc_undet_delta_w0.2",  "gen-3 undetached rerun + delta-token CE (vs sucszd)",                        cyc(0.2, False)),
    ("cyc_det_delta_w0.05",   "detached, delta CE, low weight",                                             cyc(0.05, True)),
    ("cyc_undet_delta_w0.05", "undetached, delta CE, low weight (central arm)",                             cyc(0.05, False)),
    ("cyc_det_delta_w0.01",   "detached, delta CE, minimal weight",                                         cyc(0.01, True)),
    ("cyc_undet_delta_w0.01", "undetached, delta CE, minimal weight",                                       cyc(0.01, False)),
    ("cyc_gtreader_w0.05",    "GT-trajectory reader with delta CE (Phase-A redo done right, low weight)",   cyc(0.05, True, gt=True)),
    ("cyc_gtreader_w0.2",     "GT-trajectory reader with delta CE at gen-3 weight",                         cyc(0.2, True, gt=True)),
    ("cyc_placebo_w0.05",     "placebo control: shuffled pairing, undetached central arm settings",         cyc(0.05, False, shuffle=True)),
    ("cyc_tripwire_n03",      "steganography tripwire: central undetached arm + 0.3m trajectory noise",     cyc(0.05, False, noise=0.3)),
    ("cyc_undet_delta_w0.05_s7", "seed-7 replicate of central undetached arm",                              cyc(0.05, False, seed=7)),
    ("cyc_det_delta_w0.05_s7",   "seed-7 replicate of central detached arm",                                cyc(0.05, True, seed=7)),
    ("cyc_undet_fullspan_w0.05", "delta-CE ablation: full-span CE at low weight (weight-rescue vs delta-rescue)", cyc(0.05, False, delta=False)),
    ("ctr_w0.1_bs1",          "contrastive InfoNCE only, w=0.1 (smoke-sweep sweet spot), matched bs=1",     con(0.1)),
    ("ctr_w0.5_bs1",          "contrastive InfoNCE only, w=0.5, matched bs=1",                              con(0.5)),
    ("combo_c0.1_cyc0.05",    "combined: contrastive w=0.1 + undetached delta-CE cycle w=0.05",             con(0.1, cycle=cyc(0.05, False))),
]

outdir = pathlib.Path(__file__).parent
for tag, desc, overrides in ARMS:
    fname = f"abl_{tag}.yaml"
    job = "simlingo-abl-" + tag.replace("_", "-").replace(".", "")
    wandb = f"smoke_abl_{tag}"
    text = TEMPLATE.format(
        desc=desc, fname=fname, job=job, wandb=wandb,
        overrides="\n".join(f"      - {o}" for o in overrides),
    )
    (outdir / fname).write_text(text)
    print(f"wrote {fname}  job={job}")
